export const FEATURE_FLAG_LIST_REQUEST = 'FEATURE_FLAG_LIST_REQUEST'
export const FEATURE_FLAG_LIST_SUCCESS = 'FEATURE_FLAG_LIST_SUCCESS'
export const FEATURE_FLAG_LIST_FAIL = 'FEATURE_FLAG_LIST_FAIL'
